import { Dimensions, Platform } from "react-native";
import { Colors } from "./CustomColor";

export const CustomStyles = {
  headerContainer: {
    paddingTop: 30,
    paddingHorizontal: 16,
    paddingBottom: 12,
    backgroundColor: Colors.white,
  },
  headerContainerFav: {
    paddingTop: 30,
    paddingHorizontal: 16,
    paddingBottom: 18,
    backgroundColor: Colors.white,
  },
  headerTitle: {
    fontSize: 20,
    fontWeight: "bold",
    fontFamily: "poppins-medium",
    textAlignVertical: "center",
    includeFontPadding: false,
  },
  headerTitleWhite: {
    fontSize: 20,
    fontWeight: "bold",
    fontFamily: "poppins-medium",
    textAlignVertical: "center",
    includeFontPadding: false,
    color: Colors.white,
  },
  headerTitleContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  categoryListContainer: {
    marginVertical: 12,
  },
  categoryListContainerShort: {
    marginVertical: 6,
  },
  cardItemContainer: {
    justifyContent: "center",
    alignItems: "center",
    marginRight: 14,
  },
  imageContainer: {
    width: "100%",
    height: 180,
    marginTop: 6,
  },
  image: {
    width: "100%",
    height: "100%",
    resizeMode: "stretch",
  },
  titleText: {
    fontSize: 13,
    fontWeight: "100",
    fontFamily: "poppins-medium",
    maxWidth: (Dimensions.get("window").width - 100) / 2 - 28,
    textAlignVertical: "center",
    includeFontPadding: false,
    color: Colors.black,
  },
  titleContainer: {
    flexDirection: "row",

    alignItems: "center",
    justifyContent: "space-between",
    marginTop: 4,
  },
  heartIcon: {
    marginVertical: 6,
  },
  productContainer: {
    paddingHorizontal: 6,
    paddingTop: 6,
  },
  priceContainer: {
    marginVertical: 4,
  },
  priceText: {
    fontSize: 11,
    fontFamily: "poppins-medium",
    color: Colors.black,
  },
  bottomPaddingInList: {
    paddingBottom: 300,
  },
  bottomButtonContainer: {
    position: "absolute",
    bottom: 80,
    right: 50,
    width: 60,
    height: 60,
    borderRadius: 30,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: Colors.pink,
    elevation: 5,
    shadowColor: "black",
    shadowOffset: { height: 2, width: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 30,
    borderRadius: 30,
    overflow: Platform.OS === "android" ? "hidden" : "visible",
  },
  mainContainer: {
    paddingHorizontal: 18,
    paddingVertical: 12,
  },
  titleAndPrice: {},
  titleTextLarge: {
    fontSize: 20,
    fontFamily: "poppins-medium",
    marginRight: 8,
    marginVertical: 8,
    color: Colors.black,
  },
  titleFormLarge: {
    fontSize: 22,
    fontFamily: "poppins-medium",
    marginRight: 8,
    marginVertical: 12,
    color: Colors.black,
  },
  priceTextLarge: {
    color: Colors.gray5,
    fontSize: 15,
    fontFamily: "poppins-medium",
  },
  originalTitle: {
    fontSize: 12,
    color: Colors.gray3,
    fontFamily: "poppins-regular",
  },
  originalTitleLarge: {
    fontSize: 16,
    color: Colors.gray4,
    fontFamily: "poppins-regular",
  },
  originalTitleLargeCenter: {
    fontSize: 16,
    color: Colors.gray5,
    fontFamily: "poppins-regular",
    textAlign: "center",
    marginVertical: 12,
  },
  divider: {
    height: 3,
    marginVertical: 16,
  },
  dividerShort: {
    height: 4,
    marginTop: 24,

    width: 150,
    alignSelf: "center",
    backgroundColor: Colors.gray2,
  },
  descriptionTextMedium: {
    color: Colors.gray3,
    fontSize: 14,
    fontFamily: "poppins-regular",
  },
  descriptionTextMediumCenter: {
    color: Colors.gray3,
    fontSize: 12,
    fontFamily: "poppins-regular",
    textAlign: "center",
    marginBottom: 12,
  },

  imageContainerLarge: {
    width: Dimensions.get("window").width,
    height: 300,
  },
  iconContainers: {
    position: "absolute",
    top: 10,
    flexDirection: "row",
    justifyContent: "space-between",
    paddingHorizontal: 12,
    width: "100%",
  },
  textInput: {
    width: "100%",
    height: 50,
    borderRadius: 12,
    borderTopColor: Colors.white,
    borderTopWidth: 2,
    borderBottomWidth: 2,
    borderBottomColor: Colors.gray1,
    borderLeftWidth: 2,
    borderLeftColor: Colors.gray1,
    borderRightWidth: 2,
    borderRightColor: Colors.gray1,
    paddingHorizontal: 18,
    fontSize: 16,
    color: Colors.gray5,
    overflow: Platform.OS === "android" ? "hidden" : "visible",
    fontFamily: "poppins-medium",
    textAlignVertical: "center",
    includeFontPadding: false,
  },
  textInputIcon: {
    width: "100%",
    height: 50,
    borderRadius: 12,
    paddingHorizontal: 18,
    fontSize: 16,
    color: Colors.gray5,
    overflow: Platform.OS === "android" ? "hidden" : "visible",
    fontFamily: "poppins-medium",
    textAlignVertical: "center",
    includeFontPadding: false,
  },
  labeltext: {
    color: Colors.lightBlack,
    fontSize: 14,
    fontFamily: "poppins-regular",
  },
  labelcontainer: {
    marginVertical: 10,
  },
  error: {
    paddingVertical: 4,
    fontSize: 12,
    fontFamily: "poppins-regular",
    color: "red",
  },
  submitButton: {
    paddingHorizontal: 24,
    paddingVertical: 9,
    borderRadius: 22,
    backgroundColor: Colors.pink,
    justifyContent: "center",
    alignItems: "center",
  },
  submitButtonText: {
    fontSize: 16,
    fontFamily: "poppins-medium",
    color: Colors.white,
    textAlignVertical: "center",
    includeFontPadding: false,
  },
  submitButtonOuter: {
    marginVertical: 24,
  },
  submitButtonOuterCenter: {
    flex: 1,
    marginVertical: 48,

    alignItems: "center",
  },
  pressed: {
    opacity: 0.7,
  },
  headerIcons: {
    flexDirection: "row",
  },
  hearticon: {
    paddingHorizontal: 24,
  },
  arrowicon: {
    marginRight: 18,
  },
  backArrow: {
    // marginHorizontal: 6,
    flexDirection: "row",
    justifyContent: "center",
  },
  categoryImage: {
    width: 50,
    height: 50,
    borderRadius: 25,
    resizeMode: "stretch",
  },
  categoryImageContainer: {
    width: 50,
    height: 50,
    borderRadius: 25,
  },
  carousel: {
    marginTop: 12,
    width: "100%",
  },
  generalContainer: {
    flex: 1,
  },
  logoContainer: {
    flex: 0.35,
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
    backgroundColor: Colors.pink,
    justifyContent: "center",
    alignItems: "center",
  },
  logoContainerUpper: {
    flex: 0.35,
    borderBottomLeftRadius: 22,
    borderBottomRightRadius: 22,
    backgroundColor: Colors.pink,

    alignItems: "center",
  },
  logoImage: {
    width: 180,
    height: 60,
    borderRadius: 60,
  },
  inputContainers: {
    flex: 0.65,
    backgroundColor: Colors.appBackground,
    paddingHorizontal: 24,
    justifyContent: "center",
    alignItems: "center",
  },
  textInputContainer: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderColor: Colors.gray2,
    borderWidth: 2,
    width: "100%",
    height: 50,
    fontSize: 16,
    color: Colors.gray5,
    overflow: Platform.OS === "android" ? "hidden" : "visible",
    fontFamily: "poppins-medium",
    textAlignVertical: "center",
    includeFontPadding: false,
  },
  generalContainerCenter: {
    flex: 0.85,
    justifyContent: "center",
  },
  textInputContainerIcon: {
    paddingHorizontal: 24,
    paddingVertical: 8,
    borderTopColor: Colors.white,
    borderTopWidth: 2,
    borderBottomWidth: 2,
    borderBottomColor: Colors.gray1,
    borderLeftWidth: 2,
    borderLeftColor: Colors.gray1,
    borderRightWidth: 2,
    borderRightColor: Colors.gray1,
    width: "100%",
    height: 50,
    borderRadius: 12,
    overflow: Platform.OS === "android" ? "hidden" : "visible",
    backgroundColor: Colors.appBackground,
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
  },
  loginSignupButton: {
    flexDirection: "row",
    flex: 0.15,
    marginTop: 24,
  },
  signupButton: {
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
  },
  signupButtonFocused: {
    justifyContent: "center",
    alignItems: "center",
    flex: 1,
    borderBottomWidth: 2,
    borderBottomColor: Colors.pink,
  },
  signupTextFocused: {
    fontSize: 16,
    color: Colors.pink,
    fontFamily: "poppins-regular",
  },
  signupText: {
    fontSize: 16,
    color: Colors.gray2,
    fontFamily: "poppins-regular",
  },
  scrollView: {
    backgroundColor: Colors.appBackground,
    flex: 1,
  },
  forgotPasswordContainer: {
    alignItems: "flex-end",
    paddingVertical: 4,
  },
  forgotPasswordText: {
    fontSize: 12,
    fontFamily: "poppins-regular",
    color: Colors.pink,
  },
  forgotHeaderContainer: {
    paddingTop: 30,
    alignItems: "center",
  },
  otpInput: {
    width: "100%",
    height: 30,
    borderBottomColor: Colors.pink,
    borderBottomWidth: 2,
    marginVertical: 6,
    fontSize: 18,
    fontFamily: "poppins-medium",
    color: Colors.gray4,
    textAlign: "center",
  },
  customButtonContainer: {
    top: -30,
    justifyContent: "center",
    alignItems: "center",
    elevation: 5,
    shadowColor: "black",
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 3.5,
  },
  customButton: {
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: Colors.pink,
    elevation: 5,
    shadowColor: "black",
    shadowOffset: { height: 10, width: 0 },
    shadowOpacity: 0.25,
    shadowRadius: 3.5,
  },
  profileContainer: {
    flex: 0.65,
    paddingHorizontal: 24,
  },
  infoContainer: {
    //marginVertical: 12,
  },
  profileBottomContainer: {
    paddingTop: 124,
  },
  marginHor: {
    marginVertical: 12,
    // paddingHorizontal: 24,
    //backgroundColor: Colors.lightPink,
  },
  bestDealsText: {
    fontSize: 22,
    fontFamily: "poppins-medium",
    color: Colors.lightPink,
    textAlign: "center",
  },
  bestDealsTextYellow: {
    fontSize: 22,
    fontFamily: "poppins-medium",
    color: Colors.yellow,
    textAlign: "center",
  },
  dealsContainer: {
    backgroundColor: Colors.appBackground,
    alignItems: "center",
    paddingVertical: 8,
  },
};
